language: php
php:
    - 5.5
    - 5.6
    - hhvm

#matrix:
 # allow_failures:
  #- php: hhvm

before_install:
- sudo apt-get update > /dev/null

before_script:
   - sudo apt-get install apache2
   - sudo a2enmod rewrite

  # setup hosts file
  - VHOST=$(cat <<EOF
  <VirtualHost *:80>
      DocumentRoot "%TRAVIS_BUILD_DIR%/public"
      <Directory "%TRAVIS_BUILD_DIR%/public">
          AllowOverride All
          Require all granted
      </Directory>
  </VirtualHost>
  EOF
  )
  - echo "${VHOST}" > /etc/apache2/sites-available/default

   # configure apache virtual hosts
   #- sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default

   - sudo service apache2 restart
   # composer
   - composer self-update
   - composer install --prefer-source --no-interaction --dev
   # go to tests folder
   - cd tests

# run unit tests, create result file
script: phpunit --configuration phpunit.xml --coverage-text --coverage-clover=coverage.clover

# gets tools from Scrutinizer, uploads unit tests results to Scrutinizer (?)
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover